{
 "title": "minitwit_main_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "itu-minittwit-app" },
   {
    "name": "instance",
    "query": "twit-swarm-test-8-worker-0:8080"
   },
   { "name": "Route", "query": "/metrics" },
   { "name": "Method", "query": "GET" }
  ]
 },
 "panels": [
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..|5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Total followers ",
   "type": "stat",
   "description": "The amount of people follow other people",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM follower " }
   ]
  },
  {
   "title": "Total tweets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM message" }
   ]
  },
  {
   "title": "Current connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_current_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM user" }
   ]
  },
  {
   "title": "Total created user(template) ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{controller=\"Register\", code=\"302\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}