# Configuration file version
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: Prometheus
    # <string, required> Sets the data source type.
    type: prometheus
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: prometheus_datasource
    # <string> Sets the data source's URL, including the
    # port.
    url: http://prometheus:9090
    # <string> Sets the database user, if necessary.
    user:
    # <string> Sets the database name, if necessary.
    database:
    # <bool> Enables basic authorization.
    basicAuth:
      false
    # <string> Sets the basic authorization username.
    basicAuthUser:
    # <bool> Enables credential headers.
    withCredentials:
    # <bool> Toggles whether the data source is pre-selected
    # for new panels. You can set only one default
    # data source per organization.
    isDefault:
      true
    # <map> Fields to convert to JSON and store in jsonData.
    jsonData:
    # <map> Fields to encrypt before storing in jsonData.
    secureJsonData:
    # <int> Sets the version. Used to compare versions when
    # updating. Ignored when creating a new data source.
    version: 1
    # <bool> Allows users to edit data sources from the
    # Grafana UI.
    editable: true

# Old mssql connection, remove later
  # - name: Minitwit-database
  #     type: mssql
  #     access: proxy
  #     orgId: 1
  #     uid: minitwit-database
  #     url: ${DB_CONN_URL}
  #     user: ${DB_CONN_USER}
  #     database:
  #       minitwit-db
  #     basicAuth:
  #       false
  #     basicAuthUser:
  #       ${DB_CONN_USER}
  #     withCredentials:
  #     isDefault:
  #       false
  #     jsonData:
  #     secureJsonData:
  #       password: ${DB_CONN_PASSWORD}
  #     version: 1
  #     editable: true

  - name: minitwit-postgres
    type: postgres
    uid: minitwit-postgres
    url: ${DB_CONN_URL}
    orgId: 1
    user: ${DB_CONN_USER}
    secureJsonData:
      password: ${DB_CONN_PASSWORD}
    jsonData:
      database: postgres
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      #postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
